services:
  db:
    image: postgis/postgis:16-3.4
    container_name: parking-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_password
    ports:
      - "5432:5432"
    volumes:
      - parking_db_data:/var/lib/postgresql/data

volumes:
  parking_db_data:
