services:
  db:
    image: postgis/postgis:16-3.4
    container_name: parking-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: parking_db
      POSTGRES_USER: parking_user
      POSTGRES_PASSWORD: parking_password
    ports:
      - "5432:5432"
    volumes:
      - parking_db_data:/var/lib/postgresql/data
      - ./database/schema/schema.sql:/docker-entrypoint-initdb.d/10_schema.sql

  api:
    build: .
    container_name: parking-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  parking_db_data:      
